### ISSUE TITLE
gravity_well.tscn not working?

### ISSUE THREAD

**Issue by geekrelief** [Demindiro/godot_rapier3d#16]
Now I'm not sure if I have things setup properly.  I assumed gravity_well.tscn is supposed to attract all the balls to the origin, but the balls just fall. Is there some setting I missed?

**Comment by Demindiro** [comment]
I guess something has changed between 3.2 and 3.3, as it has stopped working for me too. I'll take a look at it.

**Comment by geekrelief** [comment]
Oh great! Thanks for taking a look.  I'm running off 3.x. I'll be diving into rust and rapier, and hopefully I'll be able to contribute more.
