### ISSUE TITLE
Does this work with Godot 3.3 or is this a 4.0 exlusive module?

### ISSUE THREAD

**Issue by ValorZard** [Demindiro/godot_rapier3d#34]
With the references to the PhysicsServer in the documentation, this seems like something built for 4.0. I'm really hoping that this could work with 3.3 as well though. Sorry for all of the questions by the way, I'm just very excited about this project.

**Comment by Demindiro** [comment]
It is built for 3.3. The `PhysicsServer` also exists in Godot 3
