### ISSUE TITLE
godot_rapier3d\addons\rapier3d\lib folder never created on Windows

### ISSUE THREAD

**Issue by Kair0ss** [Demindiro/godot_rapier3d#42]
When you build the library is this folder supposed to be created? After I built Godot and the library and ran Godot (both in the benchmark and a new project), CMD was being spammed with `Not Implemented` errors and I realised in the debugger it said it couldn't find `rapier3d.dll` in this folder, the folder didn't even exist. I just created the folder myself and put the dll in it (which I found in `godot_rapier3d\target\x86_64-pc-windows-msvc\release\deps`) and it fixed the issue, but it's not supposed to be like that is it?

**Comment by Demindiro** [comment]
It seems the build script for Windows as well as for Linux indeed misses a command to create the `lib/` folder.
